### ISSUE TITLE
Wrangle data and assign it back to its original object

### ISSUE THREAD

**Issue by jasonbaik94** [rstudio-education/tidyverse-cookbook#3]
You want to use `tidyverse` expressions to manipulate a dataset and then assign the resulting dataset back to its original object. 

You don't want to repeat the name of the object twice. For example:

```{r}
starwars <- starwars %>%
    group_by(species) %>%
    summarise(avg_height = mean(height, na.rm = TRUE))
```

#### Solution {-}

```{r}
starwars %<>%
    group_by(species) %>% 
    summarise(avg_height = mean(height, na.rm = TRUE))
```

#### Discussion {-}

The `%<>%` operator (pronounced "compound assignment operator")  is used to update a variable by first piping it into one or more right hand side expressions (ex. `group_by` and `summarise`), and then assigning the result back into the object.

It saves you the extra step of typing the assignment operator and the variable name again. 

The authors of the renown [R for Data Science](https://r4ds.had.co.nz/) present a contrary opinion to the  compound assignment operator. 

> I’m not a fan of this operator because I think assignment is such a special operation that it should always be clear when it’s occurring. In my opinion, a little bit of duplication (i.e. repeating the name of the object twice) is fine in return for making assignment more explicit.

What this boils down to whether you prefer writing concise code (`%<>%`) or readable and clear code (repeating the name of the object twice with `%>%`).

**Comment by garrettgman** [comment]
@jasonbaik94 thanks for the recipe, and the tweet! Can you put this into a pull request, so I can merge it into the book. Here's how:

1. Go to https://rstudio-education.github.io/tidyverse-cookbook/program.html
2. Then click the icon at the top of the page that looks like this <img width="36" alt="screen shot 2018-12-05 at 11 47 42 am" src="https://user-images.githubusercontent.com/85014/49533053-a1937580-f883-11e8-950b-ddd56cd90bc1.png">. This will open a copy of the raw file for the chapter, which is a great place to learn the formatting tricks you are asking about on twitter.
3. Paste in your recipe from above at the bottom of the page. 
4. Try to make the formatting match the formatting of the other recipes. Don't stress: I can clean up afterwards for you.
5. Once you are done, use the wizard at the bottom of the page to submit a pull request. This will ping me to take a look.

Thanks

**Comment by jasonbaik94** [comment]
Done!
